SELECT SUM(CITY.POPULATION)
FROM CITY
JOIN COUNTRY 
ON CITY.CountryCode = COUNTRY.Code
WHERE COUNTRY.CONTINENT = 'Asia';



-- CITY + COUNTRY
--       ↓
-- JOIN
--       ↓
-- Keep CONTINENT = 'Asia'
--       ↓
-- SUM(POPULATION)